In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [24]:
model_lg = LogisticRegression()
model_svm = SVC()
model_rf  = RandomForestClassifier()

In [4]:
from sklearn.datasets import load_digits

In [5]:
digits = load_digits()

# K-fold cross validation

Basic example

In [6]:
from sklearn.model_selection import KFold

In [7]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return(model.score(x_test,y_test))


In [30]:
score_lg = []
score_svm = []
score_rf = []

for train_index,test_index in kf.split(digits.data, digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]
    score_lg.append(get_score(model_lg, x_train,x_test,y_train,y_test))
    score_svm.append(get_score(model_svm, x_train,x_test,y_train,y_test))
    score_rf.append(get_score(model_rf, x_train,x_test,y_train,y_test))
    print('next')

    

c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


next


c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


next


In [29]:
score_lg

[0.8943270300333704, 0.9276169265033407]

In [31]:
score_svm

[0.9510567296996663, 0.9610244988864143]

In [32]:
score_rf

[0.9210233592880979, 0.9242761692650334]

Stratified kfolf

In [37]:
from sklearn.model_selection import StratifiedKFold

In [39]:
s_kf = StratifiedKFold(n_splits=3)

In [40]:
score_lg = []
score_svm = []
score_rf = []

for train_index,test_index in s_kf.split(digits.data, digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]
    score_lg.append(get_score(model_lg, x_train,x_test,y_train,y_test))
    score_svm.append(get_score(model_svm, x_train,x_test,y_train,y_test))
    score_rf.append(get_score(model_rf, x_train,x_test,y_train,y_test))
    print('next')

c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


next


c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


next


c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


next


In [41]:
score_lg

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [42]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [43]:
score_rf

[0.9432387312186978, 0.9465776293823038, 0.9232053422370617]

## Cross_val_score function

In [33]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(LogisticRegression(),digits.data, digits.target, cv=3)

c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

array([0.92153589, 0.94156928, 0.91652755])

In [44]:
cross_val_score(SVC(),digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [46]:
cross_val_score(model_rf,digits.data, digits.target, cv=3)

array([0.93989983, 0.95492487, 0.92988314])

## Iris dataset

In [48]:
from sklearn.datasets import load_iris

In [49]:
iris = load_iris()

In [50]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Cross validation

In [60]:
score_lg = cross_val_score(model_lg, iris.data, iris.target, cv=10 )
np.average(score_lg)

c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\ayush yadav\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

0.9733333333333334

In [61]:
score_svm = cross_val_score(model_svm, iris.data, iris.target, cv=10 )
np.average(score_svm)

0.9733333333333334

In [71]:
score_rf  = cross_val_score(RandomForestClassifier(n_estimators=100), iris.data, iris.target, cv=10 )
np.average(score_rf)

0.96

In [67]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
score_tree  = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=10 )
np.average(score_tree)

0.9533333333333334